version: "3.8"

networks:
    default:
        name: my-network

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: kohona-app
        restart: always
        volumes:
            - ./:/var/www/html:rw
        environment:
            - APP_ENV=production
            - APP_DEBUG=false
            - DEBUGBAR_ENABLED=false
            - APP_KEY=${APP_KEY}
            - DB_CONNECTION=pgsql
            - DB_HOST=db
            - DB_PORT=5432
            - DB_DATABASE=kohona
            - DB_USERNAME=root
            - DB_PASSWORD=root
        depends_on:
            - db
        networks:
            - default
    nginx:
        image: nginx:stable-alpine
        container_name: kohona-nginx
        volumes:
            - ./:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:rw
        depends_on:
            - web
        networks:
            - default
        ports:
            - 80:80
            - 443:443
        expose:
            - 80
            - 443
    db:
        image: postgres:alpine
        container_name: kohona-db
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=kohona
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - ./postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        expose:
            - 5432
